
using System.Collections.Generic;

namespace OpenImis.ePayment.Escape.Payment.Models
{
    public static class GepgCodeResponses
    {

        public static readonly Dictionary<string, int> GepgResponseCodes
          = new Dictionary<string, int>
          {
              { "Successful", 7101 },
              { "Failure", 7201 },
              { "Header Not Given", 7202 },
              { "Unauthorized", 7203 },
              { "Bill Not Exist", 7204 },
              { "Invalid Service Provider", 7205 },
              { "Service Provider Not Active", 7206 },
              { "Duplicate Payment", 7207 },
              { "Invalid Business Account", 7208 },
              { "Business Account Not Active", 7209 },
              { "Collection Account Balance Limit Reached", 7210 },
              { "Payment Service Provider Code Not Match Bill Service Provider Code", 7211 },
              { "Payment Currency Did Not Match Bill Currency", 7212 },
              { "Bill Has Expired", 7213 },
              { "Insufficient Amount Paid", 7214 },
              { "Invalid Payment Service Provider", 7215 },
              { "Payment Service Provider Not Active", 7216 },
              { "No Payer Email Or Phone Number", 7217 },
              { "Wrong Payer Identity", 7218 },
              { "Wrong Currency", 7219 },
              { "Sub Service Provider Inactive", 7220 },
              { "Wrong Bill Equivalent Amount", 7221 },
              { "Wrong Bill Miscellaneous Amount", 7222 },
              { "Invalid Or Inactive Gfs Or Service Type", 7223 },
              { "Wrong Bill Amount", 7224 },
              { "Invalid Bill Reference Number Or Code", 7225 },
              { "Duplicate Bill Information", 7226 },
              { "Blank Bill Identification Number", 7227 },
              { "Invalid Sub Service Provider", 7228 },
              { "Wrong Bill Item GFS Or Payment Type Code", 7229 },
              { "Wrong Bill Generation Date", 7230 },
              { "Wrong Bill Expiry Date", 7231 },
              { "Consumer Already Started By Another Process", 7232 },
              { "Consumer Already Stopped By Another Process", 7233 },
              { "Wrong Bill Payment Option", 7234 },
              { "Bill Creation Completed Successfully", 7235 },
              { "Bill Creation Completed With Errors", 7236 },
              { "Bill Detail Creation Completed Successfully", 7237 },
              { "Bill Detail Creation Completed With Errors", 7238 },
              { "No External Bill System Settings Found", 7239 },
              { "Failed To Save Transaction", 7240 },
              { "Invalid Session", 7241 },
              { "Invalid Request Data", 7242 },
              { "Invalid Credit Account", 7243 },
              { "Invalid Transfer Amount", 7244 },
              { "Invalid Credit Account Name", 7245 },
              { "Invalid Debit Account", 7246 },
              { "Invalid Transfer Transaction Description", 7247 },
              { "Invalid Debitor Bic", 7248 },
              { "Wrong Transfer Date", 7249 },
              { "Invalid value in transfer reserved field one", 7250 },
              { "Invalid transfer transaction number", 7251 },
              { "Transfer transaction created successfully", 7252 },
              { "Transfer transaction created with errors", 7253 },
              { "Invalid use payment reference, use 'Y' or 'N'", 7254 },
              { "Invalid item billed amount", 7255 },
              { "Invalid item equivalent amount", 7256 },
              { "Invalid item miscellaneous amount", 7257 },
              { "Total item billed amount mismatches the bill amount", 7258 },
              { "Total item equivalent amount mismatches the bill equivalent amount", 7259 },
              { "Total item miscellaneous amount mismatches the bill miscellaneous amount", 7260 },
              { "Defect bill saved successfully", 7261 },
              { "Defect bill saved with errors", 7262 },
              { "Defect bill items saved successfully", 7263 },
              { "Defect bill items saved with errors", 7264 },
              { "Bill items saved successfully", 7265 },
              { "Bill items saved with errors", 7266 },
              { "Invalid email address", 7267 },
              { "Invalid phone number", 7268 },
              { "Invalid or inactive Service Provider System Id", 7269 },
              { "Transfer transaction update completed successfully", 7270 },
              { "Transfer transaction update completed with errors", 7271 },
              { "Defect transfer transaction saved successfully", 7272 },
              { "Defect transfer transaction saved with errors", 7273 },
              { "Duplicate transfer transaction", 7274 },
              { "Invalid Service Provider Payer Id", 7275 },
              { "Invalid Service Provider Payer Name", 7276 },
              { "Invalid bill description", 7277 },
              { "Invalid bill approval user", 7278 },
              { "Bill already settled", 7279 },
              { "Bill expired and bill move process failed", 7280 },
              { "Invalid payment transaction date", 7281 },
              { "Invalid payer email or phone number", 7282 },
              { "Bill has been cancelled", 7283 },
              { "Payment currency did not match collection account currency", 7284 },
              { "Invalid bill generation user", 7285 },
              { "Bill cancellation process failed", 7286 },
              { "Bill reference number does not meet required bill control number specifications", 7287 },
              { "Disbursement request did not match signature", 7288 },
              { "Invalid batch generated date", 7289 },
              { "Total batch amount cannot be zero(0)", 7290 },
              { "Total batch amount is not equal to summation of items(transactions)", 7291 },
              { "Duplicate disbursement batch", 7292 },
              { "Invalid disbursement pay option", 7293 },
              { "Invalid disbursement batch scheduled date", 7294 },
              { "Invalid disbursement notification template", 7295 },
              { "Disbursement notification template is not active", 7296 },
              { "Inactive currency", 7297 },
              { "Invalid currency for disbursement", 7298 },
              { "Batch item(recipients) recipients should not exceed", 7299 },
              { "Bill has been paid partially", 7301 },
              { "Paid amount is not exact billed amount", 7302 },
              { "Invalid Signature", 7303 },
              { "Invalid Signature Configuration missing one of parameter (passphrase,keyalias,filename)", 7304 },
              { "Invalid batch start and end date", 7305 },
              { "Batch has no item(transaction)", 7306 },
              { "lbl.message.0107 = Inconsistency batch start, end and generated date", 7307 },
              { "Invalid value in transfer reserved field two", 7308 },
              { "Invalid value in transfer reserved field three ", 7309 },
              { "Invalid transfer credit or debit account", 7310 },
              { "Invalid GePG configurations missing one of parameter (gepgKeyFilePath,gepgPassphrase,gepgAlias)", 7311 },
              { "Batch does not exist", 7312 },
              { "Cancel is only for auto pay batch", 7313 },
              { "Batch already on disbursement process, cancellation process failed", 7314 },
              { "Batch cancellation process failed", 7315 },
              { "Batch already canceled", 7316 },
              { "Error on processing request", 7317 },
              { "Invalid reconciliation request date", 7318 },
              { "Reconciliation request date is out of allowable range", 7319 },
              { "Invalid reconciliation request options", 7320 },
              { "Request can not completed at this time, try later", 7321 },
              { "Inactive communication protocol", 7322 },
              { "Invalid code, mismatch of supplied code on information and header", 7323 },
              { "No payment(s) found for specified bill control number", 7324 },
              { "Request to partner application composed", 7325 },
              { "Request sent to partner application(system)", 7326 },
              { "Request sent to partner application(system) with no content response", 7327 },
              { "Request not received successful with partner application(system)", 7328 },
              { "Processing or communication error on partner application(system)", 7329 },
              { "Inactive or Unavailable, bill push to pay for specified Payment service Provider", 7330 },
              { "Paid Online Waiting Bank Confirmation", 7331 },
              { "Too many request of the same content", 7332 },
              { "Invalid bill control number", 7333 },
              { "Bill has been updated", 7334 },
              { "Requested bill control number does not exist", 7335 },
              { "Requested bill amount has reached the maximum payable limit", 7336 },
          };
    }
}
