name: create docker image
on:
  push:
    branches:
      - master
      - develop
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the openimis restapi  Docker image
      run: |
         docker build . --tag ghcr.io/openimis/openimis-rest_api:${GITHUB_REF##*/}
         docker push ghcr.io/openimis/openimis-rest_api:${GITHUB_REF##*/}
