name: create manual docker image 
on:
  workflow_dispatch:
    inputs:   
      tag:
        required: true
      buildvariant:
        required: true
        default: "Release"

jobs:
  publish-manual-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the openimis backend  Docker image
      run: |
         docker build . --build-arg BUILD-FLAVOUR=${{ github.event.inputs.buildvariant }} --tag ghcr.io/openimis/openimis-rest_api:${{ github.event.inputs.tag }}
         docker push ghcr.io/openimis/openimis-rest_api:${{ github.event.inputs.tag }}
